### ISSUE TITLE
How do i get the code

### ISSUE THREAD

**Issue by Hacks-lol** [knosmos/checkers#1]
How do i get the code for my buddy to join?

**Comment by knosmos** [comment]
Click on "create game", it should open a page with "waiting for other player..." and the game code:
![image](https://user-images.githubusercontent.com/30610197/108211904-457f3980-70fb-11eb-8473-795cd5f306bf.png)

Be patient, sometimes the server takes a while to load since it's a free hosting server.

**Comment by Hacks-lol** [comment]
ah i see 
https://bottlecap-checkers.herokuapp.com/
herokuapp urls dont work for my network 
can i get the code and run that on a diffent site
(probs 000hosting)

**Comment by Hacks-lol** [comment]
no wait its in the code
lol im blind
